### ISSUE TITLE
OCI image building

### ISSUE THREAD

**Issue by n-zhang-hp** [MatrixAI/Emergence#46]
Investigate methods to build OCI images and management via Nix. Start with building something similar to dockerTools in nixpkgs.

---

### Tasks:

- [x] Ability to build a new single layer image from scratch
- [x] Ability to build layered image from single layer images
- [x] Reference existing layers when building layered image instead of full copy
- [x] Copy runtime dependencies to image local nix store
- [ ] Handle whiteout files
- [ ] Support nested layered image building
- [ ] Option to flatten layered image
- [ ] Support extra commands
- [ ] Fetching image from registries
- [ ] Build new image on top of fetched image

**Comment by CMCDragonkai** [comment]
@n-zhang-hp please check these related issues:

* https://github.com/MatrixAI/Emergence/issues/37
* https://github.com/MatrixAI/Emergence/issues/23
* https://github.com/MatrixAI/Emergence/issues/22

If they are related, please assign yourself there, or associate them into the relevant project board.

**Comment by n-zhang-hp** [comment]
An initial ociTools attempt can be found here. 891b92bbe5561035e504891a7da99e47f9d39582
Closes #23

**Comment by n-zhang-hp** [comment]
The initial ociTools simply fetches packages from nixpkgs and dump them into oci image spec compatible images. This works for `oci-image-tool` and `runc`.

However, relevant paths for dynamic linking inside a container are different from nix environment or even unavailable. 

We could either do static linking for packages with `gcc .... -static` (need to bring in `glibc.static` in this case) or use `patchelf` to modify paths for required dynamic libraries.

Or alternatively, this could be operator's responsibility to create properly linked/formed binary/library files.

**Comment by n-zhang-hp** [comment]
For nix based artefacts, instead of copying closures into image layers, we can mount host nix store inside an automaton. Containers built this way will be really lightweight comparing to shipping all dependencies around. 

This does require a host nix store to be present and has the outputs the automaton depends on. 

Also, when an automaton is transferred between nodes, its closure must also be serialised and delivered.

**Comment by n-zhang-hp** [comment]
Closing this in favour of #51 since our main objective for now is running OCI image based and Nix based artefacts rather than building OCI image with nix.

**Comment by n-zhang-hp** [comment]
Closing this in favour of #51 since our main objective for now is running OCI image based and Nix based artefacts rather than building OCI image with nix.
